<a href="https://colab.research.google.com/github/kimys0279/Kaggle/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
test_array = np.array(['1', '4', 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [7]:
test_array = np.array([1, 4, 5, '8'], float)
print(test_array)
print(type(test_array[3]))
print(test_array.dtype)
print(test_array.shape)

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [8]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [11]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor, int).shape 

(4, 3, 4)

In [12]:
np.array(tensor, int).ndim

3

In [13]:
np.array(tensor, int).size

48

In [14]:
np.array([[1, 2, 3], [4.5, 5, 6]], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype = np.float32) #float32 = 4byte > 24byte

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [16]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype = np.float64) #float64 = 8byte > 48byte

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]])

In [18]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype = int) #int = 1byte > 6byte

array([[1, 2, 3],
       [4, 5, 6]])

Reshape

In [19]:
test_matrix = [[1, 2, 3, 4], [1,2, 5, 8]]
np.array(test_matrix).shape 

(2, 4)

In [20]:
np.array(test_matrix).reshape(8, )

array([1, 2, 3, 4, 1, 2, 5, 8])

In [21]:
np.array(test_matrix).reshape(8, ).shape

(8,)

In [22]:
np.array(test_matrix).reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [25]:
a = np.array(test_matrix).reshape(2, 2, 2)
a.size

8

In [24]:
np.array(test_matrix).reshape(2, 2,2).shape

(2, 2, 2)

In [27]:
a.reshape(1, 1, -1, 2)

array([[[[1, 2],
         [3, 4],
         [1, 2],
         [5, 8]]]])

In [28]:
a.reshape(4, -1)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

Flatten- 1차원 형태로 바꿔줌

In [29]:
a.flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

Indexing and SLicing

In [31]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)

[[1 2 3]
 [4 5 6]]


In [32]:
print(a[0, 0])

1


In [33]:
print(a[0][0])

1


In [41]:
a[0, 0] =a[0, 1] = 12
print(a)

[[12 12  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [38]:
a[1, 1:3]

array([7, 8])

In [39]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

Creation Function

In [42]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [44]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
np.arange(0, 5, 0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3,
 1.4000000000000001,
 1.5,
 1.6,
 1.7000000000000002,
 1.8,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1000000000000005,
 4.2,
 4.3,
 4.4,
 4.5,
 4.6000000000000005,
 4.7,
 4.800000000000001,
 4.9]

ones, zeros and empty

In [46]:
np.zeros(shape = (10, ), dtype = np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(shape = (10, ), dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [49]:
np.empty(shape = (10, ), dtype = np.int) #이상한 값이 들어있음: 메모리 위치만 잡을 뿐이라 예전에 남아있던 값들이 잡히는 것. 초기화시켜주지 않음

array([93922053311696,              0,              0,              0,
                    0,              0,              0,              0,
                    0,              0])

In [51]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

identity

In [55]:
np.identity(n = 3, dtype = np.int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [58]:
np.eye(N=3, M=5, dtype=np.int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [59]:
np.eye(3, 5, k=2) #이게 identity 보다 조금 더 범용성 있을듯

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix) # 대각선 값 뽑아오기

array([0, 4, 8])

In [61]:
np.diag(matrix, k= 1)

array([1, 5])

In [64]:
np.random.uniform(0, 1, 10).reshape(2, 5) #균등분포

array([[0.15942805, 0.57965056, 0.78300662, 0.0922205 , 0.25688106],
       [0.19189659, 0.84559604, 0.91986465, 0.6804586 , 0.25471044]])

In [65]:
np.random.normal(0, 1, 10).reshape(2, 5) #정규분포

array([[-0.15363992, -0.77593526, -0.5370567 , -0.96592878, -0.80365657],
       [-0.15407532,  0.0682952 , -0.5264365 , -0.58500107,  0.5757001 ]])

Operation Function

In [66]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
test_array.sum(dtype = np.float)

55.0

In [68]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
test_array.sum(axis = 1), test_array.sum(axis = 0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [76]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [77]:
third_order_tensor.sum(axis = 2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [78]:
third_order_tensor.sum(axis = 1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [79]:
third_order_tensor.sum(axis = 0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [80]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
test_array.mean(), test_array.mean(axis = 0)

(6.5, array([5., 6., 7., 8.]))

In [82]:
test_array.std(), test_array.std(axis = 0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [84]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

concatenate - 합치기

In [85]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [88]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [89]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [93]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

Array Operation

In [96]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [95]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [97]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
test_a * test_a #shape 가 같으면 matrix 내 같은 위치끼리 곱셈

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [100]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [102]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

In [103]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [105]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

In [106]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [107]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [108]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [109]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [110]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [111]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [112]:
def scalar_vector_product(scalar, vector):
  result = []
  for value in vector:
    result.append(scalar*value)
  return result

iteration_max = 100000000

vector = list(range(iteration_max))
scalar = 2

In [114]:
%timeit scalar_vector_product(scalar, vector)

1 loop, best of 5: 12.4 s per loop


In [115]:
%timeit [ scalar * value for value in range(iteration_max)]

1 loop, best of 5: 11 s per loop


In [116]:
%timeit np.arange(iteration_max) * scalar

1 loop, best of 5: 255 ms per loop


Comparison

In [117]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.any(a>5), np.any(a<0)

(True, False)

In [119]:
np.all(a>5), np.all(a<10)

(False, True)

In [120]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [121]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [122]:
test_a == test_b

array([False, False, False])

In [123]:
(test_a > test_b).any()

True

In [125]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [126]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [129]:
c = np.array([False, True, True], bool)
np.logical_or(b,c)

array([False,  True,  True])

In [130]:
np.where(a > 0, 3, 2) #where(condition, TRUE, FALSE)

array([3, 3, 2])

In [131]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9]),)

In [132]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [133]:
np.isfinite(a)

array([ True, False, False])

argmax, argmin

In [135]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a) #index값 반환

(5, 0)

In [136]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
np.argmax(a, axis = 1), np.argmin(a, axis = 0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

Boolean Index
numpy 는 특정 조건에 따른 값을 추출 가능
comparison operation 함수 사용 가능

In [137]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [138]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [139]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

fancy index

In [140]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) #index 값
a[b]

array([2., 2., 4., 8., 6., 4.])

In [141]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [144]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 0, 1], int)
a[b,c]

array([ 1.,  4., 16.,  9.,  4.])

numpy data i/o

In [ ]:
a = np.loadtxt("./population.txt")
a[:10]

In [148]:
a_int = a.astype(int)
a_int[:3]

array([[ 1,  4],
       [ 9, 16]])

In [150]:
np.savetxt('int_data.csv', a_int, fmt = '%d', delimiter="\t")

numpy object -npy

In [152]:
np.save('npy_test.npy', arr = a_int)

In [155]:
npy_array = np.load(file = 'npy_test.npy')
npy_array[:1]

array([[1, 4]])